@echo off
echo Starting Notes Application...

echo Compiling Java files...
javac -d target/classes src/main/java/com/fred/notesapp/*.java src/main/java/com/fred/notesapp/*/*.java

echo Running application...
java -cp target/classes com.fred.notesapp.NotesAppApplication